name: 'GitHub Frame Generator'
description: 'Generate a Farcaster frame from a GitHub repository'
author: 'vrypan'

branding:
  icon: 'book'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  domain:
    description: 'The domain where the frame will be hosted'
    required: false
    default: ''
  branch:
    description: 'The branch to use for the frame'
    required: false
    default: 'gh-frame'

runs:
  using: "composite"
  steps:
    # First checkout the action repository
    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
        repository: vrypan/gh-frame
        path: action
        fetch-depth: 0

    # Then checkout the target repository
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        path: target
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ${{ github.workspace }}/action
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Generate frame
      working-directory: ${{ github.workspace }}/action
      run: python main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DOMAIN: ${{ inputs.domain }}
        BRANCH: ${{ inputs.branch }}

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
      shell: bash

    - name: Commit and push changes
      working-directory: ${{ github.workspace }}/target
      run: |
        # Check if branch exists
        if ! git show-ref --verify --quiet refs/heads/${{ inputs.branch }}; then
          # Create new branch from current HEAD
          git checkout -b ${{ inputs.branch }}
        else
          # Switch to existing branch
          git checkout ${{ inputs.branch }}
        fi

        # Add generated files
        git add index.html

        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update static page"
          git push origin ${{ inputs.branch }}
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}