name: 'Farcaster-friendly Repo Page'
description: 'Creates a Farcaster-friendly static page from your README.md with automatic frame support'
author: 'vrypan'

branding:
  icon: 'book'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
      shell: bash

    - name: Run Action
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_CNAME: ${{ inputs.cname }}
        GITHUB_TOKEN: ${{ inputs.token }}

inputs:
  token:
    description: 'GitHub token for repository access'
    required: true
    default: ''
  cname:
    description: 'Custom domain for GitHub Pages (optional)'
    required: false
    default: ''