name: 'Farcaster-friendly Repo Page'
description: 'Creates a Farcaster-friendly static page from your README.md with automatic frame support'
author: 'vrypan'

branding:
  icon: 'book'
  color: 'blue'

runs:
  using: 'node20'
  pre: 'npm install sharp'
  main: 'dist/index.js'

inputs:
  token:
    description: 'GitHub token for repository access'
    required: true
    default: ''
  cname:
    description: 'Custom domain for GitHub Pages (optional)'
    required: false
    default: '' 