name: 'Farcaster-friendly Repo Page'
description: 'Creates a Farcaster-friendly static page from your README.md with automatic frame support'
author: 'vrypan'

branding:
  icon: 'book'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: '${{ github.token }}'
  cname:
    description: 'Custom domain for GitHub Pages'
    required: false
  branch_name:
    description: 'Branch name for GitHub Pages'
    required: false
    default: 'gh-frame'

permissions:
  contents: write
  pages: write

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git nodejs npm
      shell: bash
    
    - name: Install Node.js dependencies
      run: |
        cd ${{ github.action_path }}
        npm install
        npm run build
      shell: bash

    - name: Get OG Image
      run: |
        chmod +x ${{ github.action_path }}/generate-images.sh
        ${{ github.action_path }}/generate-images.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        CNAME: ${{ inputs.cname }}
        BRANCH_NAME: ${{ inputs.branch_name }}

    - name: Generate static page
      run: |
        node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        CNAME: ${{ inputs.cname }}
        BRANCH_NAME: ${{ inputs.branch_name }}

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      shell: bash

    - name: Create or switch to gh-frame branch
      run: |
        if git show-ref --verify --quiet refs/heads/gh-frame; then
          git checkout gh-frame
        else
          git checkout -b gh-frame
        fi
      shell: bash

    - name: Commit generated files
      run: |
        # Only add files that exist
        for file in og-image.png splash-image.png index.html styles.css; do
          if [ -f "$file" ]; then
            git add "$file"
          fi
        done
        
        # Add CNAME if it exists and is provided
        if [ -n "$CNAME" ] && [ -f "CNAME" ]; then
          git add CNAME
        fi
        
        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update static page with generated images"
        fi
      shell: bash
      env:
        CNAME: ${{ inputs.cname }}

    - name: Pull remote changes and push
      run: |
        # Pull remote changes with rebase
        git pull --rebase origin gh-frame || true
        
        # Push changes
        git push origin gh-frame
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}