name: Build Static Page

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install sharp for linux-x64
        run: npm install --os=linux --cpu=x64 sharp

      - name: Build Static Page
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 