name: Build Static Page

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Static Page
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 