name: Test GitHub Frame Generator Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/test-action.yml'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run GitHub Frame Generator
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: 'gh-frame-test' 